name: 'Deploy to Test Flight'
description: 'Build and sign iOS app then deploy to Test Flight'
runs:
  using: "composite"
  steps:
    - name: Cache Pods
      uses: actions/cache@v2
      id: podcache
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
    - name: Install Pods
      run: cd ios && pod install && cd ..
    - name: Import signing certificate
      env:
        IOS_DIST_SIGNING_KEY: ${{ secrets.IOS_DIST_SIGNING_KEY }}
        IOS_DIST_SIGNING_KEY_PASSWORD: ${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}
      run: |
        exec .github/scripts/import-certificate.sh
    - name: Import provisioning profile
      env:
        PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
      run: |
        exec .github/scripts/import-profile.sh
    - name: Upload app to Test Flight
      env:
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_PRIVATE_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
        ASC_APPLE_ID: ${{ secrets.ASC_APPLE_ID }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      working-directory: ./ios
      run: |
        bundle exec fastlane beta
