# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_PRIVATE_KEY"],
      is_key_content_base64: true,
      in_house: false # detecting this via ASC private key not currently supported
    )
    increment_build_number(xcodeproj: "TestBareRnCi.xcodeproj")
    build_app(workspace: "TestBareRnCi.xcworkspace", scheme: "TestBareRnCi")
    upload_to_testflight(skip_waiting_for_build_processing: true)
    commit_version_bump(xcodeproj: "TestBareRnCi.xcodeproj", message: "Version bump")
    push_to_git_remote
  end
end
