name: Android

on:
  push:
    branches:
    - main
  release:
    types: [prereleased]
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Cache Gradle
      uses: actions/cache@v2
      id: gradlecache
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    - name: Cache npm dependencies
      uses: actions/cache@v2
      id: npmcache
      with:
        path: '~/.npm'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: npm test
    - name: Deploy to Google Play
      if: github.event_name == 'release' && github.event.action == 'prereleased'
      uses: ./.github/actions/deploy-to-googleplay
      with:
        KEYSTORE_DATA: ${{ secrets.KEYSTORE_DATA }}
        PLAY_CREDENTIALS: ${{ secrets.PLAY_CREDENTIALS }}
        KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
        KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
