name: iOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Set up ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
        working-directory: ./ios
        bundler-cache: true
    - name: Cache npm dependencies
      uses: actions/cache@v2
      id: npmcache
      with:
        path: '~/.npm'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: npm test
    - name: Deploy to Test Flight
      if: startsWith(github.ref, 'refs/tags/v')
      uses: ./github/actions/deploy-to-testflight
