name: iOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [prereleased]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Set Checkout Ref
      run: |
        if [[ -n $RELEASE_REF ]]; then
          echo "REF_TO_CHECKOUT=$RELEASE_REF" >> $GITHUB_ENV
        else
          echo "REF_TO_CHECKOUT=$GITHUB_REF" >> $GITHUB_ENV
        fi
      env:
        RELEASE_REF: ${{ github.event.release.target_commitish }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.REF_TO_CHECKOUT }}
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Cache npm dependencies
      uses: actions/cache@v2
      id: npmcache
      with:
        path: '~/.npm'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: npm test
    - name: Cache Pods
      uses: actions/cache@v2
      id: podcache
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
    - name: Install Pods
      run: cd ios && pod install && cd ..
    - name: Deploy to Test Flight
      if: github.event_name == 'release' && github.event.action == 'prereleased'
      uses: ./.github/actions/deploy-to-testflight
      with:
        IOS_DIST_SIGNING_KEY: ${{ secrets.IOS_DIST_SIGNING_KEY }}
        IOS_DIST_SIGNING_KEY_PASSWORD: ${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}
        PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
        ASC_APPLE_ID: ${{ secrets.ASC_APPLE_ID }}
        APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
